### ISSUE TITLE
When posting a checkbox input via FormData it fails validation

### ISSUE THREAD

**Issue by kristoferjoseph** [beginner-corp/validator#2]
It looks like this line is keeping FormData from being parsed
https://github.com/beginner-corp/validator/blob/main/src/validate.js#L11

Testing with removing this check causes forms to process checkbox inputs correctly.

**Comment by kristoferjoseph** [comment]
I did some more testing and this is not the issue. 
Still looking.

**Comment by macdonst** [comment]
I see where the validator falls down. 

If you POST url form encoded data it the validator:

1. Changes the form to a nested object. That is, if you have something like address.street it turns it into { address: { street: "" } }
2. Encodes strings into ints, booleans objects.
3. Then it runs the JSON Schema Validator.

If you POST JSON data it just:

1. Runs the JSON Schema Validator

So if you have a checkbox which is checked it's value is the string, "on", which will fail validation.
